development:
  adapter: postgresql
  database: chat_app_development
  host: localhost
  port: 5432
  password: 12345678
  username: root

production:
  adapter: postgresql
  database: chat_app_development
  host: localhost
  port: 5432
  password: 12345678
  username: root
