development:
  adapter: postgresql
  encoding: unicode
  database: chat_app_development
  # user_name: 
  # pass_word: 

production:
  adapter: postgresql
  encoding: unicode
  database: chat_app_development
  # user_name: 
  # pass_word: 